## Experiment 7 :
Write a Pandas program to get the powers of an array values element-wise.

In [ ]:
import pandas as pd

In [ ]:
df=pd.DataFrame({'X':[2,3,4,2,10], 'Y':[2,3,3,4,2],'Z':[2,3,2,4,3]})
df

    X  Y  Z
0   2  2  2
1   3  3  3
2   4  3  2
3   2  4  4
4  10  2  3

In [ ]:
p = (df.X**df.Y)**df.Z

In [ ]:
print(p)

0         16
1      19683
2       4096
3      65536
4    1000000
dtype: int64

In [ ]:
df['Power_ans'] = p
df

    X  Y  Z  Power_ans
0   2  2  2         16
1   3  3  3      19683
2   4  3  2       4096
3   2  4  4      65536
4  10  2  3    1000000